# 放到nacos配置
spring:
  cloud:
    # sentinel配置
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.47.129:9000

    # nacos服务发现配置
    nacos:
      discovery:
        server-addr: 192.168.47.129:8848

# actuator配置
management:
  endpoints:
    web:
      exposure:
        include: '*'

# feign配置降级、限流、熔断开启
feign:
  sentinel:
    enabled: true

# dubbo相关配置
dubbo:
  application:
    name: user-provider
  registry:
    address: nacos://192.168.47.129:8848
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.springcloudalibaba.user.rpcapi
  cloud:
    subscribed-services: shop-provider
  consumer:
    check: false

# seata相关配置
seata:
  enabled: true
  application-id: user-provider
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true

  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 192.168.47.129:8848
      group: SEATA_GROUP

  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.47.129:8848
      namespace:
