# 放到nacos配置
spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.47.129:8080

    nacos:
      discovery:
        server-addr: 192.168.47.129:8848

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user_route
          uri: lb://user-provider
          predicates:
            - Path=/user/**
        - id: shop_route
          uri: lb://shop-provider
          predicates:
            - Path=/shop/**

management:
  endpoints:
    web:
      exposure:
        include: '*'