# 放到nacos配置
customer:
  name: hello

spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.47.129:8080

    nacos:
      discovery:
        server-addr: 192.168.47.129:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true

dubbo:
  application:
    name: shop-provider
  registry:
    address: nacos://192.168.47.129:8848
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.springcloudalibaba.shop.rpcapi
  cloud:
    subscribed-services: user-provider
  consumer:
    check: false