server:
  port: 8083

spring:
  application:
    name: nacos-consumer-sample

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.47.129:8848

  main:
    allow-circular-references: true

management:
  endpoints:
    web:
      exposure:
        include: '*'